"""Poseidon2-Goldilocks parameters — the pil2-stark hash family ZisK proves with.

Round constants, internal diagonals, and round counts for the two sponge widths
ZisK reaches — 16 and 4 — transcribed from pil2-proofman v1.0.0-alpha's `fields`
crate:
https://github.com/0xPolygonHermez/pil2-proofman/blob/v1.0.0-alpha/fields/src/poseidon2_constants.rs
(regenerable: golden/ pins the same crate, and goldilocks_test.py byte-matches
every width against vectors generated by that crate).

Widths 8 and 12 are not here: they are the node widths of merkle arity 2 and 3,
and `starkStruct.merkleTreeArity` is a single per-key value — governing the
stage, constant and FRI trees alike — that ZisK fixes at 4.

The pil2 conventions these parameters encode on top of zorch's agnostic core:

- Capacity is always 4 (`CAPACITY`); the rate is width - 4 except width 4,
  whose rate pil2 fixes at 4 (the full state — used only as a compression
  primitive, never a sponge). Width 4 survives the arity narrowing because it
  is not an arity at all: it is the permutation behind pil2's grinding
  predicate.
- The external matrix is NOT zorch's default: pil2's `matmul_m4` implements
  the HorizenLabs-reference M4 ([[5,7,1,3],[4,6,1,1],[1,3,5,7],[1,1,4,6]]),
  not Plonky3's [[2,3,1,1],...] that `default_external_matrix` builds. The
  block form is the same (2x M4 on the diagonal 4-blocks, M4 off-diagonal;
  plain M4 at width 4), so the full matrix is passed explicitly per width.
  zorch#264 carries the base M4 as an `external_m4` marker attribute, which the
  compiler applies via multiply-free add-chains, so the block-structured width
  16 lowers to the dedicated `zorch.poseidon2` emitter — the fast
  commit-compile path. Width 4's plain single-block M4 is
  not marker-carried, so it stays on the generic fused region.
- The internal layer is `Diag(d) + J` (pil2's `prodadd`: out_i = d_i*x_i +
  sum), i.e. zorch's `internal_diag = d`, `internal_j_scale = 1`.
"""

from __future__ import annotations

import functools

import frx
import frx.numpy as fnp
import numpy as np
from frx import Array
from hash_frx.poseidon2.params import Poseidon2Params
from hash_frx.poseidon2.poseidon2 import Poseidon2
from zk_dtypes import goldilocks as F

WIDTHS = (4, 16)
CAPACITY = 4
RATE = {4: 4, 16: 12}
_EXTERNAL_ROUNDS = 4  # per half (4 initial + 4 terminal)
_INTERNAL_ROUNDS = {4: 21, 16: 22}
_ALPHA = 7

# pil2's matmul_m4 in matrix form (HorizenLabs reference M4) — distinct from
# Plonky3's M4 that zorch defaults to.
_M4 = [[5, 7, 1, 3], [4, 6, 1, 1], [1, 3, 5, 7], [1, 1, 4, 6]]


def _external_matrix(width: int) -> Array:
    """pil2 `matmul_external` as a matrix: per-4-block M4, then each block adds
    the M4-image column sums of all blocks — (I + J_blocks) ⊗ M4, i.e. 2x M4 on
    the diagonal blocks and M4 elsewhere. Width 4 is plain M4."""
    m = [
        [_M4[i % 4][j % 4] * (2 if i // 4 == j // 4 else 1) for j in range(width)]
        for i in range(width)
    ]
    return _u64_array(m) if width > 4 else _u64_array(_M4)


_EXTERNAL_INITIAL_4 = [
    [0x5098165EE28E503E, 0x41B84EDFEE6C0590, 0xDDA6BC081661F7B8, 0xB56F892B5FC6D76C],
    [0xB2B7E92B1F70399F, 0x7075CC44042536E9, 0xD5AAE31B4968ADB1, 0x713F06EB5E40337],
    [0x80DCCD8A419CC2D5, 0x89AE3F75C9B53E2C, 0x8AAC5449EFF27E1D, 0xEF29B2B24BF503F9],
    [0xA1D4F9EAAA62E9FC, 0x2F215D5C5A0AA622, 0x7B3447F34AE22DD9, 0x4B614218A8E81EEF],
]

_EXTERNAL_TERMINAL_4 = [
    [0xB73BDAFED7F79F4, 0x619B24EB14C29F0F, 0x85904BD8DB9E3CD9, 0x4C9C28E673ABB589],
    [0x73B20F643717949F, 0x832AB3FAA2C0639A, 0xFA1D702BAFB65207, 0x3F5F17B0409003C],
    [0x2C3FF110B39F84D5, 0x4CDFD3FF34CE6F4F, 0xD3ACF5807F208DB4, 0x13D28634CE48E600],
    [0xB065F0E667D7CAF9, 0x44F6F3D6B12825CA, 0x243A64C03F36EA35, 0x470A3B7C2F6A6A7A],
]

_INTERNAL_RC_4 = [
    0xE063343114E0F434,
    0x2CDEDF7F0717AD4E,
    0x4662C297F2537CF5,
    0x8FE48EEE51761F3D,
    0x616AEAD4AE0EBF00,
    0x9B40B73022B3089B,
    0xA051E1646094B036,
    0xF69B2C13F377FF8E,
    0x96F7DEC4549AF9BE,
    0x858371686234C707,
    0x8483EC4D5E3E8114,
    0x21AEA04A4066E649,
    0xBED21BD95C72EC7E,
    0x948655AAFAD4B757,
    0xD4B2ED65735823E2,
    0x1930EF5F54C40462,
    0xB3CC1696B1D3811E,
    0xAFE0336077202599,
    0x11DA6A906EF66E3E,
    0xD7ABDF7D347FB43F,
    0x65E7D3C9F0E8DA86,
]

_DIAG_4 = [
    0xF0CE126FE8A83094,
    0x60F87E0B59FB4EE6,
    0xA8106C221CD6D882,
    0x5529EDDC46E372E7,
]

_EXTERNAL_INITIAL_16 = [
    [
        0x15EBEA3FC73397C3,
        0xD73CD9FBFE8E275C,
        0x8C096BFCE77F6C26,
        0x4E128F68B53D8FEA,
        0x29B779A36B2763F6,
        0xFE2ADC6FB65ACD08,
        0x8D2520E725AD0955,
        0x1C2392B214624D2A,
        0x37482118206DCC6E,
        0x2F829BED19BE019A,
        0x2FE298CB6F8159B0,
        0x2BBAD982DECCDBBF,
        0xBAD568B8CC60A81E,
        0xB86A814265BAAD10,
        0xBEC2005513B3ACB3,
        0x6BF89B59A07C2A94,
    ],
    [
        0xA25DEEB835E230F5,
        0x3C5BAD8512B8B12A,
        0x7230F73C3CB7A4F2,
        0xA70C87F095C74D0F,
        0x6B7606B830BB2E80,
        0x6CD467CFC4F24274,
        0xFEED794DF42A9B0A,
        0x8CF7CF6163B7DBD3,
        0x9A6E9DDA597175A0,
        0xAA52295A684FAF7B,
        0x17B811CC3589D8D,
        0x55BFB699B6181648,
        0xC2CCAF71501C2421,
        0x1707950327596402,
        0xDD2FCDCD42A8229F,
        0x8B9D7D5B27778A21,
    ],
    [
        0xAC9A05525F9CF512,
        0x2BA125C58627B5E8,
        0xC74E91250A8147A5,
        0xA3E64B640D5BB384,
        0xF53047D18D1F9292,
        0xBAAEDDACAE3A6374,
        0xF2D0914A808B3DB1,
        0x18AF1A3742BFA3B0,
        0x9A621EF50C55BDB8,
        0xC615F4D1CC5466F3,
        0xB7FBAC19A35CF793,
        0xD2B1A15BA517E46D,
        0x4A290C4D7FD26F6F,
        0x4F0CF1BB1770C4C4,
        0x548345386CD377F5,
        0x33978D2789FDDD42,
    ],
    [
        0xAB78C59DEB77E211,
        0xC485B2A933D2BE7F,
        0xBDE3792C00C03C53,
        0xAB4CEFE8F893D247,
        0xC5C0E752EAB7F85F,
        0xDBF5A76F893BAFEA,
        0xA91F6003E3D984DE,
        0x99539077F311E87,
        0x97EC52232F9559E,
        0x53641BDF8991E48C,
        0x2AFE9711D5ED9D7C,
        0xA7B13D3661B5D117,
        0x5A0E243FE7AF6556,
        0x1076FAE8932D5F00,
        0x9B53A83D434934E3,
        0xED3FD595A3C0344A,
    ],
]

_EXTERNAL_TERMINAL_16 = [
    [
        0xDACF46DC1C31A045,
        0x5D2E3C121EB387F2,
        0x51F8B0658B124499,
        0x1E7DBD1DAA72167D,
        0x8275015A25C55B88,
        0xE8521C24AC7A70B3,
        0x6521D121C40B3F67,
        0xAC12DE797DE135B0,
        0xAFA28EAD79F6ED6A,
        0x685174A7A8D26F0B,
        0xEFF92A08D35D9874,
        0x3058734B76DD123A,
        0xFA55DCFBA429F79C,
        0x559294D4324C7728,
        0x7A770F53012DC178,
        0xEDD8F7C408F3883B,
    ],
    [
        0x39B533CF8D795FA5,
        0x160EF9DE243A8C0A,
        0x431D52DA6215FE3F,
        0x54C51A2A2EF6D528,
        0x9B13892B46FF9D16,
        0x263C46FCEE210289,
        0xB738C96D25AABDC4,
        0x5C33A5203996D38F,
        0x2626496E7C98D8DD,
        0xC669E0A52785903A,
        0xAECDE726C8AE1F47,
        0x39343EF3A81E999,
        0x2615CEAF044A54F9,
        0x7E41E834662B66E1,
        0x4CA5FD4895335783,
        0x64B334D02916F2B0,
    ],
    [
        0x87268837389A6981,
        0x34B75BCB20A6274,
        0x58E658296CC2CD6E,
        0xE2D0F759ACC31DF4,
        0x81A652E435093E20,
        0xB72B6E0172EAF47,
        0x4AEC43CEC577D66D,
        0xDE78365B028A84E6,
        0x444E19569ADC0EE4,
        0x942B2451FA40D1DA,
        0xE24506623EA5BD6C,
        0x82854BF2EF7C743,
        0x69DBBC566F59D62E,
        0x248C38D02A7B5CB2,
        0x4F4E8F8C09D15EDB,
        0xD96682F188D310CF,
    ],
    [
        0x6F9A25D56818B54C,
        0xB6CEFED606546CD9,
        0x5BC07523DA38A67B,
        0x7DF5A3C35B8111CF,
        0xAAA2CC5D4DB34BB0,
        0x9E673FF22A4653F8,
        0xBD8B278D60739C62,
        0xE10D20F6925B8815,
        0xF6C87B91DD4DA2BF,
        0xFED623E2F71B6F1A,
        0xA0F02FA52A94D0D3,
        0xBB5794711B39FA16,
        0xD3B94FBA9D005C7F,
        0x15A26E89FAD946C9,
        0xF3CB87DB8A67CF49,
        0x400D2BF56AA2A577,
    ],
]

_INTERNAL_RC_16 = [
    0x28EFF4B01103D100,
    0x60400CA3E2685A45,
    0x1C8636BEB3389B84,
    0xAC1332B60E13EFF0,
    0x2ADAFCC364E20F87,
    0x79FFC2B14054EA0B,
    0x3F98E4C0908F0A05,
    0xCDB230BC4E8A06C4,
    0x1BCAF7705B152A74,
    0xD9BCA249A82A7470,
    0x91E24AF19BF82551,
    0xA62B43BA5CB78858,
    0xB4898117472E797F,
    0xB3228BCA606CDAA0,
    0x844461051BCA39C9,
    0xF3411581F6617D68,
    0xF7FD50646782B533,
    0x6CA664253C18FB48,
    0x2D2FCDEC0886A08F,
    0x29DA00DD799B575E,
    0x47D966CC3B6E1E93,
    0xDE884E9A17CED59E,
]

_DIAG_16 = [
    0xDE9B91A467D6AFC0,
    0xC5F16B9C76A9BE17,
    0xAB0FEF2D540AC55,
    0x3001D27009D05773,
    0xED23B1F906D3D9EB,
    0x5CE73743CBA97054,
    0x1C3BAB944AF4BA24,
    0x2FAA105854DBAFAE,
    0x53FFB3AE6D421A10,
    0xBCDA9DF8884BA396,
    0xFC1273E4A31807BB,
    0xC77952573D5142C0,
    0x56683339A819B85E,
    0x328FCBD8F0DDC8EB,
    0xB5101E303FCE9CB7,
    0x774487B8C40089BB,
]

_EXTERNAL_INITIAL = {
    4: _EXTERNAL_INITIAL_4,
    16: _EXTERNAL_INITIAL_16,
}
_EXTERNAL_TERMINAL = {
    4: _EXTERNAL_TERMINAL_4,
    16: _EXTERNAL_TERMINAL_16,
}
_INTERNAL_RC = {
    4: _INTERNAL_RC_4,
    16: _INTERNAL_RC_16,
}
_DIAG = {4: _DIAG_4, 16: _DIAG_16}


def _u64_array(values: object) -> Array:
    # Round constants exceed int64; route through uint64 so the canonical
    # value, not a sign-wrapped one, converts into the field dtype.
    return fnp.array(np.array(values, dtype=np.uint64), dtype=F)


def goldilocks_params(width: int) -> Poseidon2Params:
    """pil2-stark's Poseidon2-Goldilocks parameterization for `width`."""
    if width not in WIDTHS:
        raise ValueError(f"width must be one of {WIDTHS}, got {width}")
    internal_rounds = _INTERNAL_ROUNDS[width]
    internal_rc = np.zeros((internal_rounds, width), dtype=np.uint64)
    internal_rc[:, 0] = np.array(_INTERNAL_RC[width], dtype=np.uint64)
    return Poseidon2Params(
        width=width,
        dtype=F,
        alpha=_ALPHA,
        external_rounds=_EXTERNAL_ROUNDS,
        internal_rounds=internal_rounds,
        external_constants_initial=_u64_array(_EXTERNAL_INITIAL[width]),
        external_constants_terminal=_u64_array(_EXTERNAL_TERMINAL[width]),
        internal_constants=_u64_array(internal_rc),
        internal_diag=_u64_array(_DIAG[width]),
        external_matrix=_external_matrix(width),
    )


@functools.cache
def goldilocks_perm(width: int) -> Poseidon2:
    """The pil2-stark permutation for `width` on zorch's Poseidon2 core.

    Cached per width: the permutation is immutable and its construction runs
    host-side analysis (`Poseidon2Params.__post_init__` validation, M4
    block-structure detection), so rebuilding it inside a traced region — the
    transcript and every Merkle tree call this per `prove` — both repeats that
    host work and plants a `np.asarray`-on-tracer barrier that blocks jitting
    the FRI fold loop. One concrete instance, reused, keeps the fold loop
    traceable as a single compiled function. Construction is forced eager so
    a cache miss under an ambient trace stores concrete constants, not that
    trace's tracers (the block composite's phase-1 commit traces
    `merkle_tree` before anything else has warmed the cache).
    """
    with frx.ensure_compile_time_eval():
        return Poseidon2(goldilocks_params(width))
