"""Byte-match of the Poseidon2-Goldilocks permutation against pil2-proofman.

The golden vectors are generated by golden/ from the reference's own `fields`
crate (`poseidon2_hash`), so equality here pins zorch's agnostic core +
these parameters to the exact permutation pil2-stark runs, per width.
"""

from __future__ import annotations

import json
import pathlib

import jax.numpy as jnp
import numpy as np
from absl.testing import absltest
from zk_dtypes import goldilocks_mont as F

from zisk_zorch.poseidon2.goldilocks import WIDTHS, goldilocks_perm

_GOLDEN = pathlib.Path(__file__).parent / "testdata" / "golden" / "permutation.json"


def _u64(values: list[str]) -> jnp.ndarray:
    return jnp.array(np.array([int(v) for v in values], dtype=np.uint64), dtype=F)


class GoldilocksPoseidon2Test(absltest.TestCase):
    def test_permute_matches_pil2_reference(self) -> None:
        golden = json.loads(_GOLDEN.read_text())
        widths_seen = []
        for entry in golden["widths"]:
            width = entry["width"]
            widths_seen.append(width)
            perm = goldilocks_perm(width)
            for case in entry["cases"]:
                out = perm.permute(_u64(case["input"]))
                expected = _u64(case["output"])
                self.assertTrue(
                    bool(jnp.array_equal(out, expected)),
                    msg=f"width {width}: {out} != {expected}",
                )
        self.assertCountEqual(widths_seen, WIDTHS)

    def test_no_dedicated_fusion(self) -> None:
        # pil2's M4 is the HorizenLabs reference, not the Plonky3 one zorch's
        # dedicated zkx emitter hardcodes, so every width must take the generic
        # fused-region route (correct, unfused) until zkx parameterizes the M4.
        for width in WIDTHS:
            self.assertFalse(
                goldilocks_perm(width).has_dedicated_fusion, msg=f"width {width}"
            )


if __name__ == "__main__":
    absltest.main()
