"""Byte-match of the Poseidon1-Goldilocks permutation against pil2-proofman.

The golden vectors are generated by tools/fixture-gen from the reference's own
`fields` crate (`poseidon1_hash`), so equality here pins zorch's optimized-sparse
core + these parameters to the exact permutation pil2-stark runs by default, per
width. This is the family native ZisK commits with (the installed proving key
sets no `hash`, so pil2's `DEFAULT_HASH_ID = "Poseidon1"` wins).
"""

from __future__ import annotations

import json
import pathlib

import frx.numpy as fnp
import numpy as np
from absl.testing import absltest
from zk_dtypes import goldilocks as F

from zisk_zorch.poseidon1.goldilocks import WIDTHS, goldilocks_perm

_GOLDEN = pathlib.Path(__file__).parent / "testdata" / "golden" / "permutation.json"


def _u64(values: list[str]) -> fnp.ndarray:
    return fnp.array(np.array([int(v) for v in values], dtype=np.uint64), dtype=F)


class GoldilocksPoseidon1Test(absltest.TestCase):
    def test_permute_matches_pil2_reference(self) -> None:
        golden = json.loads(_GOLDEN.read_text())
        widths_seen = []
        for entry in golden["widths"]:
            width = entry["width"]
            widths_seen.append(width)
            perm = goldilocks_perm(width)
            for case in entry["cases"]:
                out = perm.permute(_u64(case["input"]))
                expected = _u64(case["output"])
                self.assertTrue(
                    bool(fnp.array_equal(out, expected)),
                    msg=f"width {width}: {out} != {expected}",
                )
        self.assertCountEqual(widths_seen, WIDTHS)

    def test_generic_fused_region_routing(self) -> None:
        # No dedicated zorch.poseidon1 emitter: the dense full-field matrices ride
        # as closed-over field arrays (an int64 literal would overflow), so every
        # width stays on the generic fused region.
        for width in WIDTHS:
            self.assertFalse(
                goldilocks_perm(width).has_dedicated_fusion, msg=f"width {width}"
            )


if __name__ == "__main__":
    absltest.main()
