"""Byte-match of the host (numpy) Poseidon1 engine against pil2-proofman.

The permutation cases reuse the committed reference goldens — including
width 8, which the device stack cannot run (fractalyze/zorch#565) and which
is exactly the width family-1 grinding needs. The grinding triples were
generated by `PoseidonGoldilocks<8>::grinding` from pil2-stark's own
`libstarks.a` at tag v1.0.0-alpha (scalar mode)."""

from __future__ import annotations

import json
import pathlib

import numpy as np
from absl.testing import absltest

from zisk_zorch.poseidon1.goldilocks_host import (
    grind_family1,
    grind_family1_is_valid,
    permute_host,
)

_GOLDEN = pathlib.Path(__file__).parent / "testdata" / "golden" / "permutation.json"

# (challenge, pow_bits, nonce) from the native reference; smallest-nonce
# contract, so equality is exact.
_GRIND_TRIPLES = (
    ((123456789, 987654321, 555555555), 16, 170),
    ((5313280111789231076, 7833458167342527271, 13010609504215643355), 12, 685),
    ((1, 2, 3), 18, 239814),
)


class GoldilocksPoseidon1HostTest(absltest.TestCase):
    def test_permute_matches_pil2_reference_all_widths(self) -> None:
        golden = json.loads(_GOLDEN.read_text())
        widths = []
        for entry in golden["widths"]:
            width = entry["width"]
            widths.append(width)
            for case in entry["cases"]:
                inp = np.array([int(v) for v in case["input"]], dtype=np.uint64)
                want = np.array([int(v) for v in case["output"]], dtype=np.uint64)
                got = permute_host(inp[None, :], width)[0]
                self.assertTrue(
                    np.array_equal(got, want), msg=f"width {width}: {got} != {want}"
                )
        self.assertIn(8, widths)  # the grinding width must stay covered

    def test_grind_matches_pil2_reference(self) -> None:
        for chal, bits, want in _GRIND_TRIPLES:
            challenge = np.array(chal, dtype=np.uint64)
            got = grind_family1(challenge, bits)
            self.assertEqual(got, want, msg=f"pow_bits={bits}")
            self.assertTrue(grind_family1_is_valid(challenge, got, bits))

    def test_batched_permute_agrees_with_single(self) -> None:
        rng = np.random.default_rng(7)
        batch = rng.integers(0, 1 << 63, size=(5, 8), dtype=np.uint64)
        all_out = permute_host(batch, 8)
        for i in range(5):
            one = permute_host(batch[i : i + 1], 8)[0]
            self.assertTrue(np.array_equal(all_out[i], one))


if __name__ == "__main__":
    absltest.main()
