# Copyright 2026 The zisk-zorch Authors. SPDX-License-Identifier: Apache-2.0
"""Builds the `SpecifiedRanges` fixture instead of committing it.

fibonacci-square's `SpecifiedRanges` is a range-check table, so its three fixed
columns are short enough to state outright — a constant operation id, the values
it certifies, and pil2's synthesized boundary selector. Writing them out
reproduces the proving key's blob byte for byte, which is why the blob itself is
not in the tree: a reviewer can read this and a 6 KB binary they cannot.

What the generated bytes do NOT establish is the on-disk byte order, since the
reader would only be parsing what this module wrote. That claim is external and
belongs to `scripts/extract_const_fixture.py --check`, which diffs these bytes
against a real pil2 bundle. What CI still checks every run is stronger than it
sounds: `preprocessed_test` extends the generated base and byte-matches the
prover's own dumped extension, and the LDE is injective — so a base that
extends to pil2's extension IS pil2's base, values and all.
"""

from __future__ import annotations

import numpy as np

# starkStruct.nBits = 8. The last row is padding: pil2 pads a table to the
# power-of-two height and leaves the tail zeroed.
N_ROWS = 256
N_REAL_ROWS = 255

# `constPolsMap` order, which is the order the columns sit in on disk.
COL_NAMES = ("SpecifiedRanges.OPID", "SpecifiedRanges.VALS", "__L1__")

# The bus id this table answers range checks for.
_OPID = 102


def build_const_bytes() -> bytes:
    """The `.const` blob: row-major `(N_ROWS, 3)` little-endian u64, canonical."""
    cols = np.zeros((N_ROWS, len(COL_NAMES)), dtype="<u8")
    cols[:N_REAL_ROWS, 0] = _OPID
    cols[:N_REAL_ROWS, 1] = np.arange(1, N_REAL_ROWS + 1)
    cols[0, 2] = 1  # __L1__: the Lagrange basis at row 0
    return cols.tobytes()


def build_starkinfo() -> dict:
    """The `<Air>.starkinfo.json` fields `load_preprocessed` reads.

    Deliberately not the whole file. A real starkinfo carries the cExp, opening
    points, challenge maps and the rest of the proof plan; the reader touches
    three things, and fabricating the others would put values in the tree that
    nothing checks and no one can verify. `--check` compares these three against
    a real key.

    Derived from the same constants as `build_const_bytes`, so the fixture
    cannot describe one shape and contain another.
    """
    return {
        "nConstants": len(COL_NAMES),
        "starkStruct": {"nBits": N_ROWS.bit_length() - 1},
        "constPolsMap": [{"name": name, "dim": 1} for name in COL_NAMES],
    }
