"""Stage-1 trace commit — pil2-stark's `extendAndMerkelize` on zorch blocks.

extend: the trace columns are evaluations on the order-N subgroup; INTT each
column to coefficients (the native NTT's inverse carries the 1/N), then
RS-encode onto the blown-up domain shifted by coset 7 (`Goldilocks::SHIFT`) —
exactly pil2's `NTT_Goldilocks::extendPol` (INTT with coset-power scaling, NTT
on 2^nBitsExt).

commit: leaf-hash every extended row with pil2's chained linear hash and fold
the k-ary Poseidon2 tree (arity 2/3/4 -> node width 8/12/16, 4-element root) —
`MerkleTreeGL::merkelize`. The tree is zorch's MerkleTree; everything pil2 about
it (hash family, leaf convention, arity-to-width map) rides in via the blocks.
"""

from __future__ import annotations

from dataclasses import dataclass

import jax.numpy as jnp
from jax import Array, lax
from zk_dtypes import goldilocks_mont as F

from zisk_zorch.commit.linear_hash import DIGEST_ELEMS, LinearHash
from zisk_zorch.poseidon2.goldilocks import goldilocks_perm
from zorch.coding.reed_solomon import ReedSolomon
from zorch.commit.merkle import MerkleTree
from zorch.hash.compression import Compression, CompressionParams

# Goldilocks::SHIFT — the LDE coset generator pil2-stark evaluates on.
COSET_SHIFT = 7

# pil2-stark evaluates the LDE on the order-2^32 subgroup generated by
# `Goldilocks::W[32]`; zk_dtypes' canonical Goldilocks two-adic generator spans
# the same subgroup but is a different element, so `lax.ntt`'s canonical root
# would index the domain in a different order than pil2. `lax.ntt` derives its
# root as `generator^((p-1)/ntt_length)`, so passing the generator whose
# image is pil2's root makes the transform emit directly in pil2's domain order —
# eliminating the in/out domain-reorder gathers this used to need. That generator
# is `W[32]^-1` (verified against the W table: `W[32]^-1 ^((p-1)/N) == w_pil2`).
_PIL2_W32 = 7277203076849721926
# W[32]^-1, computed as a field-native inverse (no Python modular pow / raw
# modulus); `int()` because `generator=` is a host-side subgroup-generator value.
_PIL2_GENERATOR = int(F(_PIL2_W32) ** -1)

# starkinfo's merkleTreeArity -> the Poseidon2 width hashing that tree
# (MerkleTreeGL::merkelize switches arity {2,3,4} to Poseidon2Goldilocks
# {8,12,16} for both the leaf linear hash and the node hash).
_ARITY_WIDTHS = {2: 8, 3: 12, 4: 16}


def extend(trace: Array, blowup: int) -> Array:
    """LDE a (N, n_cols) evaluation matrix to (N*blowup, n_cols) on coset 7,
    rows in pil2's domain order (`extendPol` semantics).

    Both the INTT and the coset NTT run under `_PIL2_GENERATOR`, so the native
    transform indexes the domain in pil2's order directly — no domain-reorder
    gathers (see the generator note above)."""
    if trace.ndim != 2:
        raise ValueError(f"trace must be 2-D, got ndim={trace.ndim}")
    n = trace.shape[0]
    rs = ReedSolomon(
        n, blowup, F, coset_shift=jnp.array(COSET_SHIFT, F), generator=_PIL2_GENERATOR
    )
    coeffs = lax.ntt(
        trace.T, ntt_type="INTT", ntt_length=n, generator=_PIL2_GENERATOR
    )  # per-col INTT (1/N incl.)
    return rs.encode(coeffs).T


def merkle_tree(arity: int) -> MerkleTree:
    """pil2's tree for `arity`: linear-hash leaves + arity-to-1 Poseidon2 nodes,
    one width-`4*arity` permutation for both."""
    if arity not in _ARITY_WIDTHS:
        raise ValueError(f"arity must be one of {sorted(_ARITY_WIDTHS)}, got {arity}")
    perm = goldilocks_perm(_ARITY_WIDTHS[arity])
    return MerkleTree(
        LinearHash(perm),
        Compression(perm, CompressionParams(arity=arity, chunk=DIGEST_ELEMS)),
    )


@dataclass(frozen=True)
class TraceCommitment:
    """Stage-1 output: the 4-element root, the digest layers (for the query
    phase's openings), and the extended matrix (the FRI witness)."""

    root: Array
    digest_layers: list[Array]
    extended: Array


def commit_trace(trace: Array, *, blowup: int, arity: int) -> TraceCommitment:
    """pil2-stark `extendAndMerkelize`: LDE the trace, merkelize the rows."""
    extended = extend(trace, blowup)
    root, digest_layers = merkle_tree(arity).commit(extended)
    return TraceCommitment(root=root, digest_layers=digest_layers, extended=extended)
