"""Stage-1 trace commit — pil2-stark's `extendAndMerkelize` on zorch blocks.

extend: the trace columns are evaluations on the order-N subgroup; INTT each
column to coefficients (the native NTT's inverse carries the 1/N), then
RS-encode onto the blown-up domain shifted by coset 7 (`Goldilocks::SHIFT`) —
exactly pil2's `NTT_Goldilocks::extendPol` (INTT with coset-power scaling, NTT
on 2^nBitsExt).

commit: leaf-hash every extended row with pil2's chained linear hash and fold
the k-ary Poseidon2 tree (arity 2/3/4 -> node width 8/12/16, 4-element root) —
`MerkleTreeGL::merkelize`. The tree is zorch's MerkleTree; everything pil2 about
it (hash family, leaf convention, arity-to-width map) rides in via the blocks.
"""

from __future__ import annotations

from dataclasses import dataclass

import jax.numpy as jnp
from jax import Array, lax
from zk_dtypes import goldilocks as F

from zisk_zorch.commit.linear_hash import DIGEST_ELEMS, LinearHash
from zisk_zorch.poseidon2.goldilocks import goldilocks_perm
from zorch.commit.merkle import MerkleTree
from zorch.hash.compression import Compression, CompressionParams
from zorch.poly.univariate import powers

# Goldilocks::SHIFT — the LDE coset generator pil2-stark evaluates on.
COSET_SHIFT = 7

# pil2-stark evaluates the LDE on the order-2^32 subgroup generated by
# `Goldilocks::W[32]`; zk_dtypes' canonical Goldilocks two-adic generator spans
# the same subgroup but is a different element, so `lax.ntt`'s canonical root
# would index the domain in a different order than pil2. `lax.ntt` derives its
# root as `generator^((p-1)/ntt_length)`, so passing the generator whose
# image is pil2's root makes the transform emit directly in pil2's domain order —
# eliminating the in/out domain-reorder gathers this used to need. That generator
# is `W[32]^-1` (verified against the W table: `W[32]^-1 ^((p-1)/N) == w_pil2`).
_PIL2_W32 = 7277203076849721926
# W[32]^-1, computed as a field-native inverse (no Python modular pow / raw
# modulus); `int()` because `generator=` is a host-side subgroup-generator value.
_PIL2_GENERATOR = int(F(_PIL2_W32) ** -1)

# starkinfo's merkleTreeArity -> the Poseidon2 width hashing that tree
# (MerkleTreeGL::merkelize switches arity {2,3,4} to Poseidon2Goldilocks
# {8,12,16} for both the leaf linear hash and the node hash).
_ARITY_WIDTHS = {2: 8, 3: 12, 4: 16}


def extend(trace: Array, blowup: int) -> Array:
    """LDE a (N, n_cols) evaluation matrix to (N*blowup, n_cols) on coset 7,
    rows in pil2's domain order (`extendPol` semantics).

    Bit-reversed-intermediate schedule, matching pil2/sppark's `extendPol`: the
    INTT runs as Gentleman-Sande DIF (natural in → bit-reversed-order coeffs,
    written `bit_reverse(ntt(INTT))` so the NTT-fusion rewriter's consumer fold
    emits the DIF and elides the permute), and the coset NTT runs as Cooley-Tukey
    DIT on that bit-reversed input (`ntt(bit_reverse(·))`, elided by the rewriter's
    producer fold). Keeping the intermediate bit-reversed cancels both standalone
    bit-reverse kernels — each ~40% of its transform on the ZKX GPU path — while
    the final evaluations stay natural order (so the merkelize byte-match holds).

    Two index identities make it exact. Coefficient `i` (natural) evaluates on the
    coset with weight `SHIFT**i`, so on the bit-reversed coeffs the coset powers
    ride in bit-reversed order. And `bitrev_{N·blowup}(i) = bitrev_N(i)·blowup`
    for `i < N`, so zero-extending the coefficients to the blown-up domain is a
    stride-`blowup` upsample (each coeff followed by `blowup-1` zeros) rather than
    a trailing zero-pad. Both `_PIL2_GENERATOR` NTTs keep pil2's domain order.
    """
    if trace.ndim != 2:
        raise ValueError(f"trace must be 2-D, got ndim={trace.ndim}")
    n = trace.shape[0]
    n_ext = n * blowup
    cols = trace.T  # (n_cols, N): the NTTs transform the last (domain) axis.

    # DIF INTT: natural evals → bit-reversed-order coefficients (1/N included).
    coeffs = lax.bit_reverse(
        lax.ntt(cols, ntt_type="INTT", ntt_length=n, generator=_PIL2_GENERATOR),
        dimensions=(cols.ndim - 1,),
    )
    # Coset scale (bit-reversed order): coeff at natural index i by SHIFT**i.
    coset = lax.bit_reverse(powers(jnp.asarray(COSET_SHIFT, F), n), dimensions=(0,))
    coeffs = coeffs * coset
    # Zero-extend N → N·blowup as a stride-blowup upsample (see docstring).
    padded = (
        jnp.zeros(coeffs.shape[:-1] + (n, blowup), F)
        .at[..., 0]
        .set(coeffs)
        .reshape(coeffs.shape[:-1] + (n_ext,))
    )
    # DIT coset NTT on the bit-reversed input → natural-order evaluations.
    extended = lax.ntt(
        lax.bit_reverse(padded, dimensions=(padded.ndim - 1,)),
        ntt_type="NTT",
        ntt_length=n_ext,
        generator=_PIL2_GENERATOR,
    )
    return extended.T


def merkle_tree(arity: int) -> MerkleTree:
    """pil2's tree for `arity`: linear-hash leaves + arity-to-1 Poseidon2 nodes,
    one width-`4*arity` permutation for both."""
    if arity not in _ARITY_WIDTHS:
        raise ValueError(f"arity must be one of {sorted(_ARITY_WIDTHS)}, got {arity}")
    perm = goldilocks_perm(_ARITY_WIDTHS[arity])
    return MerkleTree(
        LinearHash(perm),
        Compression(perm, CompressionParams(arity=arity, chunk=DIGEST_ELEMS)),
    )


@dataclass(frozen=True)
class TraceCommitment:
    """Stage-1 output: the 4-element root, the digest layers (for the query
    phase's openings), and the extended matrix (the FRI witness)."""

    root: Array
    digest_layers: list[Array]
    extended: Array


def commit_trace(trace: Array, *, blowup: int, arity: int) -> TraceCommitment:
    """pil2-stark `extendAndMerkelize`: LDE the trace, merkelize the rows."""
    extended = extend(trace, blowup)
    root, digest_layers = merkle_tree(arity).commit(extended)
    return TraceCommitment(root=root, digest_layers=digest_layers, extended=extended)
