"""Stage-1 trace commit — pil2-stark's `extendAndMerkelize` on zorch blocks.

extend: the trace columns are evaluations on the order-N subgroup; INTT each
column to coefficients (the native NTT's inverse carries the 1/N), then
RS-encode onto the blown-up domain shifted by coset 7 (`Goldilocks::SHIFT`) —
exactly pil2's `NTT_Goldilocks::extendPol` (INTT with coset-power scaling, NTT
on 2^nBitsExt).

commit: leaf-hash every extended row with pil2's chained linear hash and fold
the k-ary tree (arity 4 -> node width 16, 4-element root) —
`MerkleTreeGL::merkelize`. The tree is zorch's MerkleTree; everything pil2 about
it (hash family, leaf convention, arity-to-width map) rides in via the blocks,
so selecting Poseidon1 or Poseidon2 only swaps the permutation the blocks hold.
"""

from __future__ import annotations

import functools

import frx.numpy as fnp
import numpy as np
from frx import Array, lax
from hash_frx.compression import Compression, CompressionParams
from zk_dtypes import goldilocks as F
from zk_dtypes import pfinfo
from zorch.coding.reed_solomon import ReedSolomon
from zorch.commit.merkle import MerkleTree

from zisk_zorch.commit.linear_hash import DIGEST_ELEMS, LinearHash
from zisk_zorch.poseidon1.goldilocks import goldilocks_perm as _poseidon1_perm
from zisk_zorch.poseidon2.goldilocks import goldilocks_perm as _poseidon2_perm
from zisk_zorch.quotient.zerofier import _PIL2_GENERATOR
from zisk_zorch.types import TraceCommitment

# Goldilocks::SHIFT — the LDE coset generator pil2-stark evaluates on.
COSET_SHIFT = 7

# pil2-stark evaluates the LDE on the order-2^32 subgroup generated by
# `Goldilocks::W[32]`; zk_dtypes' canonical Goldilocks two-adic generator spans
# the same subgroup but is a different element, so `lax.ntt`'s canonical root
# would index the domain in a different order than pil2. `lax.ntt` derives its
# root as `generator^((p-1)/ntt_length)`, so passing the generator whose image is
# pil2's root makes the transform emit directly in pil2's domain order —
# eliminating the in/out domain-reorder gathers this used to need. That generator
# is `_PIL2_GENERATOR` (`W[32]^-1`), shared from `zerofier` so the LDE and the FRI
# fold cannot disagree on which root pil2 is on.

# starkinfo's merkleTreeArity -> the permutation width hashing that tree
# (MerkleTreeGL::merkelize switches the arity to the width-4*arity permutation
# for both the leaf linear hash and the node hash).
#
# Only arity 4 is modelled — this is the one place that decision is explained;
# `tools/fixture-gen`, `transcript.WIDTH` and the poseidon modules' `WIDTHS`
# follow it. `merkleTreeArity` is one value per key that pil2-stark applies to
# the stage trees, the constant tree and the FRI layer trees alike:
# https://github.com/0xPolygonHermez/pil2-proofman/blob/v1.0.0-alpha/pil2-stark/src/starkpil/starks.hpp#L44-L70
# pil2's setup defaults it to 4 on the Goldilocks path:
# https://github.com/0xPolygonHermez/pil2-proofman/blob/v1.0.0-alpha/setup/pil2-stark/src/types/stark_struct.rs#L144-L155
# and every stark in the ZisK v1.0.0-alpha tower this repo replays — the
# 43 AIR/compressor/recursive/vadcop_final keys — declares 4. The single
# exception is `vadcop_final_compressed`, the SNARK-wrap input, which pil2
# hardcodes to arity 2 (and whose FRI would need the width-8 node hash):
# https://github.com/0xPolygonHermez/pil2-proofman/blob/v1.0.0-alpha/setup/pil2-stark/src/proving_key/compressed_final.rs#L205
# That stark is past the tower's end and unmodelled; the parameter stays so a
# key that declares anything but 4 fails loudly here rather than committing a
# root no golden pins.
_ARITY = 4
_WIDTH = 4 * _ARITY

# The hash family the merkle tree commits with. Native ZisK defaults to
# "Poseidon1" (the installed proving key sets no `hash`, so pil2's
# DEFAULT_HASH_ID wins); "Poseidon2" is the alternative some keys select. The
# LDE is family-independent — only the tree's leaf/node permutation changes.
_HASH_FAMILY_PERMS = {
    "Poseidon2": _poseidon2_perm,
    "Poseidon1": _poseidon1_perm,
}
DEFAULT_HASH_FAMILY = "Poseidon2"


_GOLDILOCKS_P = int(pfinfo(F).modulus)


@functools.cache
def _shift_inv_powers(count: int) -> np.ndarray:
    """`[7^0, 7^-1, ..., 7^-(count-1)] mod p` as canonical u64 — the coset
    unscale `unextend` applies per coefficient (cached: a Python big-int
    loop, same trap as the FRI fold's coset table)."""
    inv = pow(COSET_SHIFT, -1, _GOLDILOCKS_P)
    out = [1] * count
    for k in range(1, count):
        out[k] = out[k - 1] * inv % _GOLDILOCKS_P
    return np.array(out, dtype=np.uint64)


def unextend(extended: Array, blowup: int) -> Array:
    """Inverse of `extend`: recover the (N, n_cols) base evaluations from a
    coset-7 LDE in pil2's domain order.

    INTT on the extended domain yields the polynomial's coefficients scaled
    by `7^k`; unscale, keep the base-degree prefix (the rest vanish for a
    genuine LDE), and NTT back at base length — all on `_PIL2_GENERATOR`'s
    tower, so domain order round-trips exactly."""
    if extended.ndim != 2:
        raise ValueError(f"extended must be 2-D, got ndim={extended.ndim}")
    ne = extended.shape[0]
    n = ne // blowup
    coeffs = lax.ntt(
        extended.T, ntt_type="INTT", ntt_length=ne, generator=_PIL2_GENERATOR
    )
    unscaled = coeffs[:, :n] * fnp.array(_shift_inv_powers(ne)[:n], dtype=F)
    return lax.ntt(unscaled, ntt_type="NTT", ntt_length=n, generator=_PIL2_GENERATOR).T


# How much of an extended section one LDE block may occupy. `extend` splits
# the columns into blocks of at most this many bytes and writes each block
# into the result, so the transform's temporaries scale with a block rather
# than with the section.
#
# Three block-sized temporaries are live at the peak — the interpolated
# coefficients, the coset-scaled block on the extended domain, and the
# transform's output — so the extend's own working set settles near three
# times this. Extending the whole matrix at once is the degenerate case
# where a block is the section: it costs two extended copies beside the
# result, which on ZisK's widest constants (VirtualTableZisk0_n21, 88
# columns) is 5.50 GiB, the single allocation that set a PJRT client's
# memory floor (docs/bridge.md "Memory budget"). A section that already
# fits in one block extends exactly as it did before.
#
# 256 MiB is the measured knee on an RTX 5090: it takes the LDE from 31.9
# to 39.5 ms on those constants (2.75 GiB of temporaries down to 0.75) and
# the smaller blocks below it buy little memory for a steepening cost.
#
# The blocking stays on this side of the zorch seam because the doubling
# does: `ReedSolomon.extend` transforms the last axis of whatever it is
# given and materializes nothing extra, and it is the row-major/column-major
# turn below — pil2's section layout meeting the transform's — that puts two
# extended copies on the device at once.
LDE_BLOCK_BYTES = 256 << 20


def _block_cols(ext_rows: int, n_cols: int, block_bytes: int) -> int:
    """Columns per LDE block: as many as `block_bytes` of the extended
    domain holds, at least one and never more than the section has."""
    per_col = ext_rows * np.dtype(F).itemsize
    return max(1, min(n_cols, block_bytes // per_col))


def extend(trace: Array, blowup: int, *, block_bytes: int = LDE_BLOCK_BYTES) -> Array:
    """LDE a (N, n_cols) evaluation matrix to (N*blowup, n_cols) on coset 7,
    rows in pil2's domain order (`extendPol` semantics).

    The permute-cancelling LDE schedule lives in `ReedSolomon.extend`, which
    transforms the last axis; the trace is row-major here, so it rides in as
    columns (`trace.T`) and back out as rows. `_PIL2_GENERATOR` keeps the
    transform in pil2's domain order.

    Columns are transformed a block at a time and written into the result
    (`LDE_BLOCK_BYTES`); the bytes are the same either way, since each
    column's LDE is independent of every other's.
    """
    if trace.ndim != 2:
        raise ValueError(f"trace must be 2-D, got ndim={trace.ndim}")
    n, n_cols = trace.shape
    ne = n * blowup
    # The shift crosses an optimization barrier so XLA cannot fold the coset
    # power series it seeds into a 2^nBitsExt literal: every exported
    # program that LDEs would otherwise carry its own copy (tens of MB each,
    # on the device for as long as the program is loaded).
    rs = ReedSolomon(
        n,
        blowup,
        F,
        coset_shift=lax.optimization_barrier(fnp.asarray(COSET_SHIFT, F)),
        generator=_PIL2_GENERATOR,
    )
    cols = _block_cols(ne, n_cols, block_bytes)
    if cols == n_cols:
        return rs.extend(trace.T).T
    out = fnp.zeros((ne, n_cols), F)
    for j in range(0, n_cols, cols):
        # Ordering, not placement. The blocks are independent, so left to
        # itself XLA schedules several of their transforms at once and their
        # temporaries pile up — five blocks live at a time on the 88-column
        # constants, which is the whole allocation this is here to remove.
        # Threading the trace through the barrier with the result makes each
        # block's read depend on the previous block's write.
        trace, out = lax.optimization_barrier((trace, out))
        block = rs.extend(trace[:, j : j + cols].T).T
        out = lax.dynamic_update_slice(out, block, (0, j))
    return out


def merkle_tree(arity: int, hash_family: str = DEFAULT_HASH_FAMILY) -> MerkleTree:
    """pil2's tree for `arity`: linear-hash leaves + arity-to-1 nodes, one
    width-`4*arity` permutation of `hash_family` for both."""
    if arity != _ARITY:
        raise ValueError(f"arity must be {_ARITY}, got {arity}")
    if hash_family not in _HASH_FAMILY_PERMS:
        raise ValueError(
            f"hash_family must be one of {sorted(_HASH_FAMILY_PERMS)}, got "
            f"{hash_family!r}"
        )
    perm = _HASH_FAMILY_PERMS[hash_family](_WIDTH)
    return MerkleTree(
        LinearHash(perm),
        Compression(perm, CompressionParams(arity=arity, chunk=DIGEST_ELEMS)),
    )


def commit_trace(
    trace: Array,
    *,
    blowup: int,
    arity: int,
    hash_family: str = DEFAULT_HASH_FAMILY,
) -> TraceCommitment:
    """pil2-stark `extendAndMerkelize`: LDE the trace, merkelize the rows with the
    `hash_family` permutation."""
    extended = extend(trace, blowup)
    root, digest_layers = merkle_tree(arity, hash_family).commit(extended)
    return TraceCommitment(root=root, digest_layers=digest_layers, extended=extended)
