#!/usr/bin/env python3
"""Check the generated `SpecifiedRanges` fixture against a real pil2 bundle.

`zisk_zorch/constraints/const_fixture.py` builds the `SpecifiedRanges` `.const`
payload from a declarative spec, so no 6 KB blob is committed. That leaves one
claim nothing in CI can make: **pil2's on-disk byte order**. The generated bytes
round-trip through our own reader, so a layout we misunderstood would be
misunderstood consistently and the test would still pass, while
`load_preprocessed` pointed at a real proving key returned garbage.

This is that check. `--check` diffs the generated payload against a real
`<Air>.const` and fails on any difference, so the byte order is verified on
demand by anyone holding a bundle rather than asserted in a comment.

Bundles come from `tools/pil2-dump/`, which runs one real `genProof` against a
git-pinned pil2-proofman fork. Its README records the prove as deterministic —
two bundles from the same pin are byte-identical — so `--check` means the same
thing on any machine.

The starkinfo is checked field-by-field rather than byte-for-byte: the fixture
declares only the three the reader consumes (`nConstants`, `starkStruct.nBits`,
`constPolsMap`), and a real one carries the whole proof plan besides.

The starkinfo and the `.const` it is checked against must come from the SAME
bundle. pil2-proofman's `fibonacci-square/build3` key agrees with this capture
on every field the reader touches and their `.const` bytes are identical, but
they disagree on `starkStruct.nQueries` (371 vs 228) — different security
settings. Nothing here reads `nQueries`, so a mixed pair would go unnoticed.

Usage
-----
    python scripts/extract_const_fixture.py --check \\
        --const     <bundle>/SpecifiedRanges.const \\
        --starkinfo <bundle>/SpecifiedRanges.starkinfo.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent

sys.path.insert(0, str(_REPO))
from zisk_zorch.constraints import const_fixture  # noqa: E402


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--const", type=Path, help="real <Air>.const, to verify against")
    p.add_argument(
        "--starkinfo", type=Path, help="real <Air>.starkinfo.json, to verify against"
    )
    p.add_argument("--check", action="store_true", help="required; this only verifies")
    args = p.parse_args()

    if args.const is None and args.starkinfo is None:
        sys.exit("nothing to check: pass --const and/or --starkinfo")

    bad = 0
    if args.const is not None:
        # The claim the tests cannot make: our layout matches pil2's on disk.
        ok = args.const.read_bytes() == const_fixture.build_const_bytes()
        print(f"{'OK ' if ok else 'BAD'} .const bytes vs {args.const}")
        bad += not ok

    if args.starkinfo is not None:
        real = json.loads(args.starkinfo.read_text())
        want = const_fixture.build_starkinfo()
        got = {
            "nConstants": real["nConstants"],
            "starkStruct": {"nBits": real["starkStruct"]["nBits"]},
            "constPolsMap": [
                {"name": c["name"], "dim": c["dim"]} for c in real["constPolsMap"]
            ],
        }
        ok = got == want
        print(f"{'OK ' if ok else 'BAD'} starkinfo fields vs {args.starkinfo}")
        if not ok:
            print(f"  generated: {want}")
            print(f"  real     : {got}")
        bad += not ok

    return bad


if __name__ == "__main__":
    sys.exit(main())
