"""Composed byte-match of the pil2-mode inner prover vs a real pil2-proofman
genProof dump — a runnable, never a test.

Runs `Pil2InnerProver` over the capture's trace + proving key and seals each
stage against the dumped sections the moment it finishes. ``--max_stage=N``
runs and checks only the first N stages (1=trace commit, 2=+LogUp
witness-STD, 3=+quotient, 4=full, the default), a cheaper loop that skips
the downstream stages' compute; a
mismatch fail-fasts the same way, so the first bad seam is the last line
printed. The final positions/nonce compare is the transitively-strongest
link: the query draw seeds off the last squeeze, so equality means every
absorb in the whole schedule matched the native prove.

This tool checks the composition, not any one stage's math — each stage is
pinned in isolation (dumped inputs, one link each) by ``gates.py``, which
``gates_test`` runs over the same bundle. CPU-pinned like those gates (the
roles' jit zones hit the same #334 graphs, fractalyze/xla#334).

The reference is a host-provided native artifact, so CI never runs this.
Argless it reads the bundle named by ``ZISK_PIL2_CAPTURE`` (regenerated by
``tools/pil2-dump``; nothing is committed) and skips loudly when unset;
``--dump`` points at any capture:

    python -m zisk_zorch.verify_inner_proof --dump=<dir> \
        --instance=ag0_air0_inst0 --starkinfo=<starkinfo.json> --max_stage=2
"""

from __future__ import annotations

import argparse
import os
import pathlib
import sys
from collections.abc import Callable

import frx
import frx.numpy as fnp
import numpy as np
from zk_dtypes import goldilocks as F

from zisk_zorch.fri.queries import grind_is_valid, query_positions_for
from zisk_zorch.fri.seam import Pil2FriCode
from zisk_zorch.harness.capture import (
    CAPTURE_ENV,
    FIXTURE_INSTANCE,
    FIXTURE_STARKINFO,
    Capture,
    limbs,
)
from zisk_zorch.harness.gates import _check, _match
from zisk_zorch.harness.pil2 import transcript_width
from zisk_zorch.harness.pil2_prover import Pil2InnerProver
from zisk_zorch.harness.schedule import _fri_layer_root
from zisk_zorch.transcript.transcript import Transcript
from zisk_zorch.types import InnerWitness

# The schedule's stage names in prove order — ``--max_stage=N`` keeps the
# first N.
_STAGES = ("trace_commit", "logup_witness", "quotient", "opening")


def _as_u64(a) -> np.ndarray:
    return np.asarray(a).astype(np.uint64)


def _match_rows(label: str, dev, want, chunk_rows: int = 1 << 19) -> bool:
    """`_match(label, limbs(dev), want)` in leading-axis row blocks.

    A one-shot `limbs()` of a Keccakf-sized codeword is a ~16 GB device
    transient (split copy + D2H) that OOMs beside the prove's working set —
    and frx's async dispatch surfaces that failure at the NEXT sync point,
    outside any guard around the gate itself. Chunking bounds the transient
    to ~1 GB regardless of AIR width."""
    want = np.asarray(want)
    rows = dev.shape[0]
    per_row = want.size // rows
    for i in range(0, rows, chunk_rows):
        got = limbs(dev[i : i + chunk_rows])
        if not np.array_equal(got, want[i * per_row : i * per_row + got.size]):
            ok = _check(False, f"{label} (rows {i}..{i + chunk_rows})")
            print(f"  got:  {got}")
            print(f"  want: {want[i * per_row : i * per_row + got.size]}")
            return ok
    return _check(True, label)


def stage_checks(cap: Capture, width: int) -> dict[str, Callable[[object], bool]]:
    """One golden check per schedule stage, keyed by `prove_stages`' names.

    Every compared value is self-derived by the prover — nothing here reads
    a dumped section as an input — so together the checks seal that the
    stages COMPOSE: challenges, roots, committed sections, and the final
    query draw all equal the native prove's."""
    ss = cap.si["starkStruct"]
    want_ch = cap.u64("challenges").reshape(-1, 3)

    def challenges(claim, label: str) -> bool:
        ids = sorted(claim.challenges)
        return _match(
            label,
            np.stack([limbs(claim.challenges[i]) for i in ids]),
            want_ch[ids],
        )

    def check_trace_commit(commitment) -> bool:
        return _match("root1", _as_u64(commitment.root), cap.u64("root1"))

    def check_logup_witness(logup) -> bool:
        claim = logup.reduced_claim
        ok = challenges(claim, "stage-2 challenges")
        ok &= _match(
            "cm2 witness-STD columns",
            _as_u64(logup.reduction_proof.matrix).reshape(-1),
            cap.u64("cm2_base"),
        )
        ok &= _match("root2", _as_u64(claim.root2), cap.u64("root2"))
        agv = claim.airgroupvalues
        return ok & _match(
            "airgroup values (gsum result)",
            np.concatenate([limbs(agv[i]) for i in sorted(agv)]),
            cap.u64("airgroupvalues"),
        )

    def check_quotient(quotient) -> bool:
        ok = challenges(
            quotient.reduced_claim,
            f"challenges through stage {cap.si['nStages'] + 1}",
        )
        ok &= _match_rows(
            "quotient q", quotient.reduction_proof.codeword, cap.u64("q_ext")
        )
        return ok & _match(
            "rootQ", _as_u64(quotient.reduction_proof.root), cap.u64("rootQ")
        )

    def check_opening(opening) -> bool:
        proof = opening.reduction_proof
        ok = _match("evals", limbs(proof.evals), cap.u64("evals"))
        code = Pil2FriCode(tuple(cap.steps))
        ok &= _match(
            f"{len(proof.fri.roots)} FRI layer roots",
            np.stack([_as_u64(root) for root in proof.fri.roots]),
            np.stack(
                [
                    _as_u64(_fri_layer_root(cap, code, cap.u64(f"fri_layer{k}")))
                    for k in range(len(proof.fri.roots))
                ]
            ),
        )
        ok &= _match(
            "FRI final polynomial",
            limbs(proof.fri.final_pol),
            cap.u64(f"fri_layer{len(cap.steps) - 1}"),
        )
        # The dump carries no nonce/positions; both re-derive from the dumped
        # grinding seed (the last squeezed beta), which the equality then gates.
        seed = fnp.array(cap.u64(f"fri_beta{len(cap.steps) - 1}").astype(F))
        want_positions = query_positions_for(
            seed,
            width,
            proof.nonce,
            n_queries=ss["nQueries"],
            n_bits_ext=cap.nbe,
            hash_family=cap.hash_family,
        )
        ok &= _check(
            grind_is_valid(seed, proof.nonce, ss["powBits"], cap.hash_family),
            "grinding nonce",
        )
        return ok & _match("query positions", proof.positions, want_positions)

    return {
        "trace_commit": check_trace_commit,
        "logup_witness": check_logup_witness,
        "quotient": check_quotient,
        "opening": check_opening,
    }


def verify_composed_prove(cap: Capture, max_stage: int, backend: str = "cpu") -> bool:
    """Drive the composed prover through the first `max_stage` stages,
    byte-comparing each against the capture as it lands and stopping at the
    first mismatch.

    "verify" here means byte-match, not protocol verification: nothing
    below checks a Merkle path, evaluates a constraint at the
    out-of-domain point, or re-derives a fold — `verifier.py` does that.
    What this seals is conformance, that our prover reproduces the native
    prover's bytes."""
    prover = Pil2InnerProver(cap.pil2_key)
    ss = cap.si["starkStruct"]
    width = transcript_width(ss)
    transcript = Transcript(width, cap.hash_family)
    checks = stage_checks(cap, width)
    ok, ran = True, 0
    device = frx.devices("cpu")[0] if backend == "cpu" else frx.devices()[0]
    with frx.default_device(device):
        for name, result in prover.prove_stages(
            cap.pil2_claim(), InnerWitness(cap.trace), transcript
        ):
            ok &= checks[name](result)
            ran += 1
            if not ok:
                print("MISMATCH fail-fast — skipping the remaining stages")
                break
            if ran >= max_stage:
                break
    print(
        f"composed prove (stages 1..{ran}) byte-match: "
        + ("ALL OK" if ok else "FAILED")
    )
    return ok


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dump", type=pathlib.Path, default=None)
    ap.add_argument("--instance", default=FIXTURE_INSTANCE)
    ap.add_argument("--starkinfo", type=pathlib.Path, default=None)
    ap.add_argument(
        "--max_stage",
        type=int,
        default=len(_STAGES),
        choices=range(1, len(_STAGES) + 1),
        help="run and check only the first N stages: "
        + ", ".join(f"{i + 1}={s}" for i, s in enumerate(_STAGES)),
    )
    ap.add_argument(
        "--backend",
        choices=["cpu", "device"],
        default="cpu",
        help="cpu pins every stage to the host (small captures); device runs "
        "on the accelerator (real-scale AIRs exceed host patience)",
    )
    args = ap.parse_args()
    dump = args.dump
    if dump is None:
        bundle = os.environ.get(CAPTURE_ENV, "")
        if not bundle or not pathlib.Path(bundle).is_dir():
            print(
                f"SKIP     no capture: set {CAPTURE_ENV} to a tools/pil2-dump "
                "bundle directory (or pass --dump=) to run the composed gate"
            )
            return 0
        dump = pathlib.Path(bundle)
    cap = Capture(dump, args.instance, args.starkinfo or dump / FIXTURE_STARKINFO)
    print(
        f"instance {cap.instance}: N=2^{cap.nb} ext=2^{cap.nbe} "
        f"cm1={cap.n_cols} arity={cap.arity}"
    )
    return 0 if verify_composed_prove(cap, args.max_stage, args.backend) else 1


if __name__ == "__main__":
    sys.exit(main())
