"""Byte-match every zisk-zorch inner-proof stage against a real pil2-proofman
genProof dump.

One gate per stage, in proof order, each running the production code path on
the capture's real inputs and comparing byte-exactly against the section the
native prover dumped (``capture.Capture`` owns the bundle format, so gates
read protocol objects, never files). Field arithmetic is exact, so each gate
is equal-or-wrong.

The two expression-interpreter gates are CPU-pinned: the pinned frx wheel's
GPU backend miscompiles their fused graphs (fractalyze/xla#334).

Assumes a two-stage AIR with a single everyRow boundary (asserted) — the
ZisK / fibonacci-square shape.

A runnable, never a test — the reference is a host-provided native
artifact, so CI never runs this. Argless it reads the bundle named by
``ZISK_PIL2_CAPTURE`` (regenerated by ``tools/pil2-dump``; nothing is
committed) and skips loudly when unset; ``--dump`` points at any capture:

    python -m zisk_zorch.inner_prover.verify_inner_proof --dump=<dir> \
        --instance=ag0_air0_inst0 --starkinfo=<starkinfo.json>
"""

from __future__ import annotations

import argparse
import os
import pathlib
import sys

import frx
import frx.numpy as fnp
import numpy as np
from zk_dtypes import goldilocks as F
from zk_dtypes import goldilocksx3 as F3
from zorch.pcs.deep import open_columns

from zisk_zorch.commit.trace_commit import commit_trace
from zisk_zorch.evals.lev import compute_lev
from zisk_zorch.fri.fold import fold
from zisk_zorch.inner_prover.capture import Capture, P, cubic, limbs
from zisk_zorch.quotient.cexp_ref import _run_block
from zisk_zorch.quotient.zerofier import _coset_points, _root

_CAPTURE_ENV = "ZISK_PIL2_CAPTURE"
_FIXTURE_INSTANCE = "ag0_air2_inst5"
_FIXTURE_STARKINFO = "SpecifiedRanges.starkinfo.json"


def _check(ok: bool, label: str) -> bool:
    print(("OK       " if ok else "MISMATCH ") + label)
    return bool(ok)


def _on_cpu(fn, arg):
    """Run a jitted expression-interpreter graph on the host: the pinned frx
    GPU backend miscompiles these fused graphs (fractalyze/xla#334). The env
    must enter as a jit argument — closure-captured arrays lower as in-graph
    constants, which crashes the compiler on the zerofier coset (#67)."""
    with frx.default_device(frx.devices("cpu")[0]):
        return frx.jit(fn)(arg)


def verify_stage1_commit(cap: Capture) -> bool:
    """pil2 STEP_1: extend-and-merkelize the settled witness -> ``root1``."""
    commitment = commit_trace(cap.trace, blowup=cap.stride, arity=cap.arity)
    got = np.asarray(commitment.root).astype(np.uint64)
    return _check(
        np.array_equal(got, cap.u64("root1")), "stage-1 commit root (real witness)"
    )


def verify_stage2_witness(cap: Capture) -> bool | None:
    """pil2 CALCULATE_WITNESS_STD + IM_POLS: reproduce every STD column cm2
    commits from cm1 and the proving key alone, in dependency order — each
    column binds into the env before its reader evaluates (the gsum
    expressions read the im column; Module's ImPol reads ``gsum``).
    ``None`` = the AIR has nothing to gate here."""
    plan = cap.std_plan
    if plan is None:
        print("SKIP     stage-2 hint chaining (AIR commits no STD columns)")
        return None

    def stage2_cols(env):
        bound = dict(env["cm"])
        out = []
        for _, cid, compute in plan:
            col = compute(dict(env, cm=bound))
            bound[cid] = col
            out.append(col)
        return tuple(out)

    got = _on_cpu(stage2_cols, cap.base_env)
    assert cap.path("cm2_base").exists(), "stage-2 hint gate needs the cm2_base dump"
    cm2 = cap.u64("cm2_base").reshape(cap.n, cap.cm2_cols)
    ok = True
    for (name, cid, _), col in zip(plan, got):
        lo = cap.cmp_map[cid]["stagePos"]
        want = np.ascontiguousarray(cm2[:, lo : lo + 3]).reshape(-1)
        ok &= _check(
            np.array_equal(limbs(col), want),
            f"stage-2 witness column {name} (hint expressions)",
        )
    return ok


def verify_stage2_commit(cap: Capture) -> bool | None:
    """pil2 STEP_2 commit: extend-and-merkelize the dumped witness-STD
    columns -> ``cm2_ext`` and ``root2``."""
    if not cap.cm2_cols or not cap.path("cm2_base").exists():
        return None
    cm2_base = fnp.array(cap.u64("cm2_base").astype(F).reshape(cap.n, cap.cm2_cols))
    commitment = commit_trace(cm2_base, blowup=cap.stride, arity=cap.arity)
    ok = _check(
        np.array_equal(
            np.asarray(commitment.extended).astype(np.uint64),
            np.asarray(cap.bufs[("cm", 2)]).astype(np.uint64),
        ),
        "stage-2 extension == cm2_ext",
    )
    return ok & _check(
        np.array_equal(np.asarray(commitment.root).astype(np.uint64), cap.u64("root2")),
        "stage-2 commit root (real witness-STD columns)",
    )


def verify_quotient(cap: Capture) -> bool:
    """pil2 CALCULATE_QUOTIENT: interpret the key's composite cExp over the
    extended sections -> the prover's raw ``q`` section."""
    code = cap.cexp_code
    got = _on_cpu(lambda env: _run_block(code, env, cap.stride), cap.cexp_env)
    return _check(
        np.array_equal(limbs(got), cap.u64("q_ext")),
        f"quotient q = cExp/Z_H ({len(code)} SSA ops, real interpreter output)",
    )


def verify_evals(cap: Capture) -> bool:
    """pil2 STEP_EVALS via the production opening path: ``compute_lev``'s
    weight matrix (not zorch's ``compute_lagrange_basis``, quadratic in the
    base domain) drives ``open_columns``, whose base/extension column split
    re-permutes to evMap order for the byte compare."""
    lev = compute_lev(cap.challenge("std_xi"), list(cap.openings), cap.nb)
    is_base = [col.dtype == F for col in cap.opened_columns]
    order = [i for i, b in enumerate(is_base) if b] + [
        i for i, b in enumerate(is_base) if not b
    ]
    base = [cap.opened_columns[i] for i in order if is_base[i]]
    ext = [cap.opened_columns[i] for i in order[len(base) :]]
    got_split = open_columns(
        fnp.stack(base, axis=1) if base else fnp.zeros((cap.ne, 0), F),
        fnp.stack(ext, axis=1) if ext else fnp.zeros((cap.ne, 0), F3),
        lev,
        [cap.ev_map[i]["openingPos"] for i in order],
        stride=cap.stride,
    )
    got = fnp.zeros_like(got_split).at[np.array(order)].set(got_split)
    return _check(
        np.array_equal(limbs(got), cap.u64("evals")),
        f"evals ({len(cap.ev_map)} openings over {len(cap.openings)} points)",
    )


def verify_deep(cap: Capture) -> bool:
    """pil2 computeFRIExpression: vf2-Horner within an opening group (evMap
    order), one reciprocal per group, vf1-Horner across groups. zorch's
    ``deep_composition`` batches with one challenge's powers, so it cannot
    express this two-challenge form — the loop stays local."""
    g = int(np.asarray(_root(cap.nb)))
    z = cap.challenge("std_xi")
    vf1, vf2 = cap.challenge("std_vf1"), cap.challenge("std_vf2")
    evals_arr = cubic(cap.u64("evals"))
    domain = _coset_points(cap.nb, cap.nbe - cap.nb)

    def deep(cols, evals_arr, z, vf1, vf2, domain):
        fri = None
        for k, prime in enumerate(cap.openings):
            acc = None
            for i, e in enumerate(cap.ev_map):
                if e["openingPos"] != k:
                    continue
                term = cols[i] - evals_arr[i]
                acc = term if acc is None else acc * vf2 + term
            xi = z * fnp.array(np.uint64(pow(g, prime % cap.n, P)).astype(F))
            group = acc / (domain - xi)
            fri = group if fri is None else fri * vf1 + group
        return fri

    got = frx.jit(deep)(cap.opened_columns, evals_arr, z, vf1, vf2, domain)
    return _check(
        np.array_equal(limbs(got), cap.u64("deep_f")),
        f"DEEP polynomial (multi-opening, {len(cap.openings)} groups)",
    )


def verify_fri_chain(cap: Capture) -> bool:
    """pil2 STEP_FRI folds: chain the production ``fold`` down the layer
    schedule with the real per-layer betas, gating every layer."""
    pol = cubic(cap.u64("fri_layer0"))
    ok = _check(
        np.array_equal(limbs(pol), limbs(cubic(cap.u64("deep_f")))),
        "fri_layer0 == DEEP polynomial",
    )
    for k in range(1, len(cap.steps)):
        beta = cubic(cap.u64(f"fri_beta{k - 1}"))[0].reshape(())
        pol = fold(pol, beta, cap.nbe, cap.steps[k - 1], cap.steps[k])
        layer_ok = _check(
            np.array_equal(limbs(pol), cap.u64(f"fri_layer{k}")),
            f"fri fold layer {k} (nBits={cap.steps[k]}, real beta)",
        )
        ok &= layer_ok
        if not layer_ok:
            break
    return ok


_GATES = (
    verify_stage1_commit,
    verify_stage2_witness,
    verify_stage2_commit,
    verify_quotient,
    verify_evals,
    verify_deep,
    verify_fri_chain,
)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dump", type=pathlib.Path, default=None)
    ap.add_argument("--instance", default=_FIXTURE_INSTANCE)
    ap.add_argument("--starkinfo", type=pathlib.Path, default=None)
    args = ap.parse_args()
    dump = args.dump
    if dump is None:
        capture = os.environ.get(_CAPTURE_ENV, "")
        if not capture or not pathlib.Path(capture).is_dir():
            print(
                f"SKIP     no capture: set {_CAPTURE_ENV} to a tools/pil2-dump "
                "bundle directory (or pass --dump=) to run the byte-gates"
            )
            return 0
        dump = pathlib.Path(capture)
    cap = Capture(dump, args.instance, args.starkinfo or dump / _FIXTURE_STARKINFO)
    print(
        f"instance {cap.instance}: N=2^{cap.nb} ext=2^{cap.nbe} "
        f"cm1={cap.n_cols} arity={cap.arity}"
    )
    results = [gate(cap) for gate in _GATES]
    ok_all = all(r for r in results if r is not None)
    print("inner-proof byte-match: " + ("ALL COVERED LINKS OK" if ok_all else "FAILED"))
    return 0 if ok_all else 1


if __name__ == "__main__":
    sys.exit(main())
