"""Byte-match every zisk-zorch inner-proof stage against a real pil2-proofman
genProof dump.

Consumes a ``PIL2_DUMP_DIR`` capture (the ``dump/per-stage-genproof`` patch on
pil2-proofman): one AIR instance's witness, stage buffers, roots, and
transcript-derived challenges from an actual prove. One gate per stage, in
proof order:

- stage-1 commit root from the settled witness (``commit_trace``)
- stage-2 witness columns from cm1 + the proving key alone (hint num/den
  expressions -> ``im_single``, its running sum -> ``gsum``, and the
  materialized-denominator ``ImPol``), then the stage-2 extension and root
- quotient ``q = cExp/Z_H`` via the generalized SSA interpreter
  (``quotient.cexp_ref``) against the prover's raw ``q`` section
- evals over every wrapped opening point (``compute_lev`` + committed columns)
- the DEEP polynomial in pil2's multi-opening double-Horner form
- the FRI fold chain, layer by layer, with the real per-layer betas

Field arithmetic is exact, so each gate is equal-or-wrong. The two expression-
interpreter gates are CPU-pinned: the pinned frx wheel's GPU backend
miscompiles those specific large fused graphs (fractalyze/xla#334, fixed
upstream by xla#335/#341 — unpin on the next frx bump).

Assumes a two-stage AIR with a single everyRow boundary (asserted) — the
ZisK / fibonacci-square shape.

A runnable, never a test: the reference is a host-provided native
artifact (sp1-zorch's ``verify_prove_shard`` pattern), so CI never runs
this. Argless it reads the capture bundle named by ``ZISK_PIL2_CAPTURE``
(a real fibonacci-square prove regenerated by ``tools/pil2-dump``; nothing
is committed) and skips loudly when the variable is unset; an AIR without a
LogUp intermediate simply skips the hint-chaining gate. Point ``--dump`` at
any other capture for scale:

    python -m zisk_zorch.inner_prover.verify_inner_proof --dump=<dir> \
        --instance=ag0_air0_inst0 --starkinfo=<starkinfo.json>
"""

from __future__ import annotations

import json
import os
import pathlib
import sys
from functools import cached_property

import frx
import frx.numpy as fnp
import numpy as np
from zk_dtypes import goldilocks as F
from zk_dtypes import goldilocksx3 as F3
from zk_dtypes import pfinfo
from zorch.pcs.deep import open_columns
from zorch.utils.field import join_coeffs, split_coeffs

from zisk_zorch.commit.trace_commit import commit_trace
from zisk_zorch.evals.lev import compute_lev
from zisk_zorch.fri.fold import fold
from zisk_zorch.quotient.cexp_ref import _run_block
from zisk_zorch.quotient.gsum import grand_sum
from zisk_zorch.quotient.zerofier import _coset_points, _root, inv_zerofier

P = int(pfinfo(F).modulus)

# No capture is committed (the reference is regenerable, cf. sp1-zorch's
# SP1_JAX_FFI_LIB pattern): argless runs read the bundle directory named by
# ZISK_PIL2_CAPTURE — one real pil2-proofman genProof regenerated by
# tools/pil2-dump, plus the AIR's key artifacts. Defaults assume the
# fibonacci-square SpecifiedRanges bundle; --dump/--instance/--starkinfo
# override for other captures.
_CAPTURE_ENV = "ZISK_PIL2_CAPTURE"
_FIXTURE_INSTANCE = "ag0_air2_inst5"
_FIXTURE_STARKINFO = "SpecifiedRanges.starkinfo.json"


def _cubic(words: np.ndarray):
    """Contiguous gl64 limb triples -> a 1-D cubic device array."""
    return join_coeffs(fnp.array(words.astype(F).reshape(-1, 3)), F3)


def _check(ok: bool, label: str) -> bool:
    print(("OK       " if ok else "MISMATCH ") + label)
    return bool(ok)


class Capture:
    """One dumped AIR instance: starkinfo/expressionsinfo shape metadata plus
    lazy, cached readers for the per-stage ``<instance>_<name>.npy`` sections.
    Every gate reads through this, so file naming and limb layout live here
    and nowhere else."""

    def __init__(
        self, dump: pathlib.Path, instance: str, starkinfo: pathlib.Path
    ) -> None:
        self.dump, self.instance, self.starkinfo_path = dump, instance, starkinfo
        self.si = json.loads(starkinfo.read_text())
        assert self.si["nStages"] == 2, "buffer keys assume a two-stage AIR"
        assert len(self.si["boundaries"]) == 1, "only the everyRow zerofier is wired"
        ss = self.si["starkStruct"]
        self.nb, self.nbe = ss["nBits"], ss["nBitsExt"]
        self.n, self.ne = 1 << self.nb, 1 << self.nbe
        self.stride = 1 << (self.nbe - self.nb)
        self.arity = ss["merkleTreeArity"]
        self.steps = [s["nBits"] for s in ss["steps"]]
        self.cmp_map = self.si["cmPolsMap"]
        self.ev_map = self.si["evMap"]
        self.openings = self.si["openingPoints"]
        self.n_cols = self.si["mapSectionsN"]["cm1"]
        self.cm2_cols = self.si["mapSectionsN"].get("cm2", 0)
        self.n_customs = len(self.si.get("customCommits", []))

    def path(self, name: str) -> pathlib.Path:
        return self.dump / f"{self.instance}_{name}.npy"

    def u64(self, name: str) -> np.ndarray:
        arr = np.load(self.path(name))
        assert arr.dtype == np.uint64, f"{name}: expected u64 dump, got {arr.dtype}"
        return arr

    @cached_property
    def expressionsinfo(self) -> dict:
        return json.loads(
            (
                self.starkinfo_path.parent
                / self.starkinfo_path.name.replace("starkinfo", "expressionsinfo")
            ).read_text()
        )

    @cached_property
    def trace(self):
        """The settled stage-1 witness: hint-computed columns fill
        asynchronously during STEP_1, so the pre-commit dump can be
        incomplete — prefer the post-commit section."""
        name = "trace_post" if self.path("trace_post").exists() else "trace"
        words = self.u64(name)
        assert words.size == self.n * self.n_cols, "trace size mismatch"
        return fnp.array(words.astype(F).reshape(self.n, self.n_cols))

    @cached_property
    def bufs(self) -> dict:
        """Committed extended-domain sections, keyed like ``cmPolsMap`` stages
        (quotient rides as stage ``nStages + 1``)."""
        si, ne = self.si, self.ne
        bufs = {
            ("cm", 1): self.u64("cm1_ext").astype(F).reshape(ne, self.n_cols),
            ("const", 0): self.u64("const_ext").astype(F).reshape(ne, si["nConstants"]),
            ("cm", 3): self.u64("quotient_cm")
            .astype(F)
            .reshape(ne, si["mapSectionsN"]["cm" + str(si["nStages"] + 1)]),
        }
        if self.cm2_cols:
            bufs[("cm", 2)] = self.u64("cm2_ext").astype(F).reshape(ne, self.cm2_cols)
        for ci in range(self.n_customs):
            width = si["mapSectionsN"][si["customCommits"][ci]["name"] + "0"]
            bufs[("custom", ci)] = (
                self.u64(f"custom{ci}_ext").astype(F).reshape(ne, width)
            )
        return bufs

    def committed_column(self, entry: dict):
        """An evMap entry's committed column over the extended domain, cubic
        entries joined from their three contiguous gl64 lanes."""
        if entry["type"] == "cm":
            pm = self.cmp_map[entry["id"]]
            buf = self.bufs[("cm", pm["stage"])]
            if pm["dim"] == 1:
                return fnp.array(buf[:, pm["stagePos"]])
            lanes = buf[:, pm["stagePos"] : pm["stagePos"] + 3]
            return join_coeffs(fnp.array(np.ascontiguousarray(lanes)), F3)
        if entry["type"] == "const":
            return fnp.array(self.bufs[("const", 0)][:, entry["id"]])
        return fnp.array(self.bufs[("custom", entry["commitId"])][:, entry["id"]])

    @cached_property
    def opened_columns(self) -> list:
        return [self.committed_column(e) for e in self.ev_map]

    @cached_property
    def challenges(self):
        """The prove's transcript challenges, one cubic scalar per index."""
        return _cubic(self.u64("challenges"))

    def challenge(self, name: str):
        idx = next(
            i for i, c in enumerate(self.si["challengesMap"]) if c.get("name") == name
        )
        return self.challenges[idx].reshape(())

    def _cubic_scalar(self, words):
        return _cubic(np.asarray(words, dtype=np.uint64))[0]

    def _values_env(self, name: str, vmap: list) -> dict:
        """pil2 packs stage-1 values as one word, stage>=2 as three."""
        words = self.u64(name)
        out, off = {}, 0
        for i, v in enumerate(vmap):
            if v["stage"] == 1:
                out[i] = self._cubic_scalar([words[off], 0, 0])
                off += 1
            else:
                out[i] = self._cubic_scalar(words[off : off + 3])
                off += 3
        return out

    @cached_property
    def cexp_env(self) -> dict:
        """The SSA interpreter's operand environment over the extended domain."""
        si = self.si
        publics = self.u64("publics")
        return {
            "cm": {
                i: (
                    self.committed_column({"type": "cm", "id": i})
                    if pm["dim"] == 3
                    else fnp.array(self.bufs[("cm", pm["stage"])][:, pm["stagePos"]])
                )
                for i, pm in enumerate(self.cmp_map)
            },
            "const": {
                i: fnp.array(self.bufs[("const", 0)][:, i])
                for i in range(si["nConstants"])
            },
            "custom": {
                (ci, j): fnp.array(self.bufs[("custom", ci)][:, j])
                for ci in range(self.n_customs)
                for j in range(self.bufs[("custom", ci)].shape[1])
            },
            "challenges": dict(enumerate(self.challenges)),
            "publics": {
                i: self._cubic_scalar([publics[i], 0, 0]) for i in range(len(publics))
            },
            "airvalues": self._values_env("airvalues", si["airValuesMap"]),
            "airgroupvalues": self._values_env(
                "airgroupvalues", si["airgroupValuesMap"]
            ),
            "proofvalues": self._values_env("proofvalues", si["proofValuesMap"]),
            "zi": {0: inv_zerofier(self.nb, self.nbe - self.nb)},
        }


def _on_cpu(fn, arg):
    """Run a jitted expression-interpreter graph on the host. The env enters
    as a jit argument: closure-captured arrays lower as in-graph constants,
    which crashes the GPU compiler on the zerofier coset (#67). CPU-pinned
    because the pinned frx wheel's GPU backend miscompiles these fused
    graphs (fractalyze/xla#334; fixed upstream by xla#335/#341 — unpin on
    the next frx bump)."""
    with frx.default_device(frx.devices("cpu")[0]):
        return frx.jit(fn)(arg)


def verify_stage1_commit(cap: Capture) -> bool:
    got = commit_trace(cap.trace, blowup=cap.stride, arity=cap.arity).root
    want = cap.u64("root1")
    ok = np.array_equal(np.asarray(got).astype(np.uint64), want)
    return _check(ok, "stage-1 commit root (real witness)")


def verify_stage2_witness(cap: Capture) -> bool | None:
    """Reproduce cm2's columns from cm1 + the proving key alone: the hint
    num/den expressions give ``im_single``, its running sum ``gsum``, and
    ``ImPol`` materializes the denominator. ``None`` = nothing to gate."""
    ei = cap.expressionsinfo
    exps = {e["expId"]: e["code"] for e in ei["expressionsCode"]}
    hints = {h["name"]: h for h in ei["hintsInfo"]}
    # An AIR whose stage-2 carries no LogUp intermediate — a range check,
    # say — has no `im_col` hint and no imPol column: nothing to chain.
    im_pol_exp = next(
        (p["expId"] for p in cap.cmp_map if p["stage"] == 2 and p.get("imPol")), None
    )
    if "im_col" not in hints or im_pol_exp is None:
        print("SKIP     stage-2 hint chaining (AIR has no LogUp im column)")
        return None

    def hint_exp(field):
        v = next(f for f in hints["im_col"]["fields"] if f["name"] == field)
        return exps[v["values"][0]["id"]]

    const_base = np.fromfile(
        cap.starkinfo_path.parent
        / cap.starkinfo_path.name.replace(".starkinfo.json", ".const"),
        dtype=np.uint64,
    ).reshape(cap.n, cap.si["nConstants"])
    trace_np = np.asarray(cap.trace).astype(np.uint64)
    env = dict(
        cap.cexp_env,
        cm={i: fnp.array(trace_np[:, i].astype(F)) for i in range(cap.n_cols)},
        const={
            i: fnp.array(const_base[:, i].astype(F))
            for i in range(cap.si["nConstants"])
        },
        zi={},
    )

    def stage2_cols(e):
        num = _run_block(hint_exp("numerator"), e, 1)
        den = _run_block(hint_exp("denominator"), e, 1)
        gsum = grand_sum(num[:, None], den[:, None])
        return gsum, num / den, _run_block(exps[im_pol_exp], e, 1)

    got = _on_cpu(stage2_cols, env)
    assert cap.path("cm2_base").exists(), "stage-2 hint gate needs the cm2_base dump"
    cm2 = cap.u64("cm2_base").reshape(cap.n, cap.cm2_cols)
    ok = True
    for name, got_col, lo in [
        ("gsum", got[0], 0),
        ("im_single", got[1], 3),
        ("ImPol", got[2], 6),
    ]:
        want = np.ascontiguousarray(cm2[:, lo : lo + 3]).reshape(-1)
        ok &= _check(
            np.array_equal(np.asarray(split_coeffs(got_col)).reshape(-1), want),
            f"stage-2 witness column {name} (hint expressions)",
        )
    return ok


def verify_stage2_commit(cap: Capture) -> bool | None:
    if not cap.cm2_cols or not cap.path("cm2_base").exists():
        return None
    cm2_base = fnp.array(cap.u64("cm2_base").astype(F).reshape(cap.n, cap.cm2_cols))
    c2 = commit_trace(cm2_base, blowup=cap.stride, arity=cap.arity)
    ok = _check(
        np.array_equal(
            np.asarray(c2.extended).astype(np.uint64),
            np.asarray(cap.bufs[("cm", 2)]).astype(np.uint64),
        ),
        "stage-2 extension == cm2_ext",
    )
    return ok & _check(
        np.array_equal(np.asarray(c2.root).astype(np.uint64), cap.u64("root2")),
        "stage-2 commit root (real witness-STD columns)",
    )


def verify_quotient(cap: Capture) -> bool:
    cexp_code = next(
        e
        for e in cap.expressionsinfo["expressionsCode"]
        if e["expId"] == cap.si["cExpId"]
    )["code"]
    got = _on_cpu(lambda e: _run_block(cexp_code, e, cap.stride), cap.cexp_env)
    ok = np.array_equal(np.asarray(split_coeffs(got)).reshape(-1), cap.u64("q_ext"))
    return _check(
        ok, f"quotient q = cExp/Z_H ({len(cexp_code)} SSA ops, real interpreter output)"
    )


def verify_evals(cap: Capture) -> bool:
    """The production opening path: `compute_lev`'s Lagrange-evaluation matrix
    (NOT zorch's `compute_lagrange_basis` — that closed form is O(N²) and dies
    at real base-domain sizes) drives zorch's block-form `open_columns`, which
    wants columns split base-then-extension; the openings come back in that
    split order and are re-permuted to evMap order for the byte compare."""
    z = cap.challenge("std_xi")
    lev = compute_lev(z, list(cap.openings), cap.nb)
    is_base = [col.dtype == F for col in cap.opened_columns]
    order = [i for i, b in enumerate(is_base) if b] + [
        i for i, b in enumerate(is_base) if not b
    ]
    base = [cap.opened_columns[i] for i in order if is_base[i]]
    ext = [cap.opened_columns[i] for i in order[len(base) :]]
    got_split = open_columns(
        fnp.stack(base, axis=1) if base else fnp.zeros((cap.ne, 0), F),
        fnp.stack(ext, axis=1) if ext else fnp.zeros((cap.ne, 0), F3),
        lev,
        [cap.ev_map[i]["openingPos"] for i in order],
        stride=cap.stride,
    )
    got = fnp.zeros_like(got_split).at[np.array(order)].set(got_split)
    ok = np.array_equal(np.asarray(split_coeffs(got)).reshape(-1), cap.u64("evals"))
    return _check(
        ok, f"evals ({len(cap.ev_map)} openings over {len(cap.openings)} points)"
    )


def verify_deep(cap: Capture) -> bool:
    g = int(np.asarray(_root(cap.nb)))
    z = cap.challenge("std_xi")
    vf1, vf2 = cap.challenge("std_vf1"), cap.challenge("std_vf2")
    evals_arr = _cubic(cap.u64("evals"))
    domain = _coset_points(cap.nb, cap.nbe - cap.nb)

    # pil2 computeFRIExpression semantics: vf2-Horner within an opening group
    # (evMap order), one reciprocal per group, vf1-Horner across groups in
    # openingPoints order. zorch's `pcs.deep.deep_composition` batches with a
    # single challenge's geometric powers across all columns, so it cannot
    # express this two-challenge form — the loop stays local.
    def deep(cols, evals_arr, z, vf1, vf2, domain):
        fri = None
        for k, prime in enumerate(cap.openings):
            acc = None
            for i, e in enumerate(cap.ev_map):
                if e["openingPos"] != k:
                    continue
                term = cols[i] - evals_arr[i]
                acc = term if acc is None else acc * vf2 + term
            xi = z * fnp.array(np.uint64(pow(g, prime % cap.n, P)).astype(F))
            group = acc / (domain - xi)
            fri = group if fri is None else fri * vf1 + group
        return fri

    got = frx.jit(deep)(cap.opened_columns, evals_arr, z, vf1, vf2, domain)
    ok = np.array_equal(np.asarray(split_coeffs(got)).reshape(-1), cap.u64("deep_f"))
    return _check(ok, f"DEEP polynomial (multi-opening, {len(cap.openings)} groups)")


def verify_fri_chain(cap: Capture) -> bool:
    pol = _cubic(cap.u64("fri_layer0"))
    deep_f = _cubic(cap.u64("deep_f"))
    ok = _check(
        np.array_equal(np.asarray(split_coeffs(pol)), np.asarray(split_coeffs(deep_f))),
        "fri_layer0 == DEEP polynomial",
    )
    for k in range(1, len(cap.steps)):
        beta = _cubic(cap.u64(f"fri_beta{k - 1}"))[0].reshape(())
        pol = fold(pol, beta, cap.nbe, cap.steps[k - 1], cap.steps[k])
        got = np.asarray(split_coeffs(pol)).reshape(-1)
        layer_ok = _check(
            np.array_equal(got, cap.u64(f"fri_layer{k}")),
            f"fri fold layer {k} (nBits={cap.steps[k]}, real beta)",
        )
        ok &= layer_ok
        if not layer_ok:
            break
    return ok


def main() -> int:
    dump = instance = starkinfo = None
    for a in sys.argv[1:]:
        if a.startswith("--dump="):
            dump = pathlib.Path(a.split("=", 1)[1])
        elif a.startswith("--instance="):
            instance = a.split("=", 1)[1]
        elif a.startswith("--starkinfo="):
            starkinfo = pathlib.Path(a.split("=", 1)[1])
    if dump is None:
        capture = os.environ.get(_CAPTURE_ENV, "")
        if not capture or not pathlib.Path(capture).is_dir():
            print(
                f"SKIP     no capture: set {_CAPTURE_ENV} to a tools/pil2-dump "
                "bundle directory (or pass --dump=) to run the byte-gates"
            )
            return 0
        dump = pathlib.Path(capture)
    cap = Capture(
        dump, instance or _FIXTURE_INSTANCE, starkinfo or dump / _FIXTURE_STARKINFO
    )
    print(
        f"instance {cap.instance}: N=2^{cap.nb} ext=2^{cap.nbe} "
        f"cm1={cap.n_cols} arity={cap.arity}"
    )
    results = [
        gate(cap)
        for gate in (
            verify_stage1_commit,
            verify_stage2_witness,
            verify_stage2_commit,
            verify_quotient,
            verify_evals,
            verify_deep,
            verify_fri_chain,
        )
    ]
    ok_all = all(r for r in results if r is not None)
    print("inner-proof byte-match: " + ("ALL COVERED LINKS OK" if ok_all else "FAILED"))
    return 0 if ok_all else 1


if __name__ == "__main__":
    sys.exit(main())
