"""Byte-match the zisk-zorch inner proof against a real pil2-proofman
genProof dump — the thin driver over ``gates.GATES``.

A runnable, never a test — the reference is a host-provided native
artifact, so CI never runs this. Argless it reads the bundle named by
``ZISK_PIL2_CAPTURE`` (regenerated by ``tools/pil2-dump``; nothing is
committed) and skips loudly when unset; ``--dump`` points at any capture:

    python -m zisk_zorch.inner_prover.verify_inner_proof --dump=<dir> \
        --instance=ag0_air0_inst0 --starkinfo=<starkinfo.json>

The gate definitions live in ``gates.py``; this module only resolves the
bundle and runs them in proof order.
"""

from __future__ import annotations

import argparse
import os
import pathlib
import sys

from zisk_zorch.inner_prover.capture import Capture
from zisk_zorch.inner_prover.gates import GATES

_CAPTURE_ENV = "ZISK_PIL2_CAPTURE"
_FIXTURE_INSTANCE = "ag0_air2_inst5"
_FIXTURE_STARKINFO = "SpecifiedRanges.starkinfo.json"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dump", type=pathlib.Path, default=None)
    ap.add_argument("--instance", default=_FIXTURE_INSTANCE)
    ap.add_argument("--starkinfo", type=pathlib.Path, default=None)
    args = ap.parse_args()
    dump = args.dump
    if dump is None:
        capture = os.environ.get(_CAPTURE_ENV, "")
        if not capture or not pathlib.Path(capture).is_dir():
            print(
                f"SKIP     no capture: set {_CAPTURE_ENV} to a tools/pil2-dump "
                "bundle directory (or pass --dump=) to run the byte-gates"
            )
            return 0
        dump = pathlib.Path(capture)
    cap = Capture(dump, args.instance, args.starkinfo or dump / _FIXTURE_STARKINFO)
    print(
        f"instance {cap.instance}: N=2^{cap.nb} ext=2^{cap.nbe} "
        f"cm1={cap.n_cols} arity={cap.arity}"
    )
    results = [gate(cap) for gate in GATES]
    ok_all = all(r for r in results if r is not None)
    print("inner-proof byte-match: " + ("ALL COVERED LINKS OK" if ok_all else "FAILED"))
    return 0 if ok_all else 1


if __name__ == "__main__":
    sys.exit(main())
